spring.application.name=habitflow-api

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/habitflow

# Puerto
server.port=8081

# ✅ JWT
# Cambia este secreto por uno seguro en produccion (min 32 caracteres, base64)
jwt.secret=aGFiaXRmbG93LXNlY3JldC1rZXktcGFyYS1qd3QtMjAyNQ==
jwt.expiration=86400000
# 86400000 ms = 24 horas